name: feature_extraction
channels:
  - conda-forge
  - bioconda
  - hcc  # Added for AFNI package
  - defaults
dependencies:
  - python=3.9
  - pip
  - numpy>=1.20.0
  - scipy>=1.7.0
  - nibabel>=3.2.0
  - nilearn>=0.8.0
  - matplotlib>=3.4.0
  - pandas>=1.3.0
  - scikit-learn>=0.24.0
  - scikit-image>=0.18.0
  - snakemake>=7.0.0
  - pyyaml>=6.0
  - tqdm>=4.61.0
  - tcsh  # Required for AFNI scripts
  - h5py # Added for HDF5 file support
  - finufft # Added dependency for QM_FFT_Analysis
  - plotly # Added dependency for QM_FFT_Analysis
  # - afni # Added dependency for ReHo calculation (from hcc channel)
  - pip:
    - antspyx>=0.3.0
    - brainspace>=0.1.0
    - nolds>=0.5.2  # For Hurst exponent calculations
    - finufft==2.2.0
  # - afni # Added AFNI package # Removed duplicate/conda install 