name: feature_extraction
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.9
  - pip
  - numpy>=1.20.0
  - scipy>=1.7.0
  - nibabel>=3.2.0
  - matplotlib>=3.4.0
  - pandas>=1.3.0
  - h5py>=3.1.0
  - pybids>=0.15.1
  - pip:
    - nolds>=0.5.2
    - finufft 